### ISSUE TITLE
Error while Sending the reminders of the pending invoices

### ISSUE THREAD

**Issue by mohitsharma-22** [ColoredCow/portal#3360]
**Describe the bug**
Today, when I clicked the send reminder button, it opened the modal to send the email. Click on the Send email button throws an error.

**Screenshots**
<img width="1271" alt="Screenshot 2023-09-11 at 2 59 02 PM" src="https://github.com/ColoredCow/portal/assets/16541548/35ee24f9-5ab5-4d4f-90b9-a797301ded9f">

<img width="779" alt="Screenshot 2023-09-11 at 3 00 16 PM" src="https://github.com/ColoredCow/portal/assets/16541548/1208b8b8-3693-493a-ad31-1212f618c933">

<img width="872" alt="Screenshot 2023-09-11 at 3 01 22 PM" src="https://github.com/ColoredCow/portal/assets/16541548/03a209f2-e4f2-47b6-a33f-278e44e13f60">

**Comment by Satendra-SR** [comment]
```php
[2023-09-11 23:59:03] production.ERROR: Call to undefined method Modules\Project\Services\ProjectService::getMailForFixedBudgetProjectKeyAccountManagers() {"exception":"[object] (Error(code: 0): Call to undefined method Modules\\Project\\Services\\ProjectService::getMailForFixedBudgetProjectKeyAccountManagers() at /var/www/html/portal.coloredcow.com/Modules/Project/Console/FixedBudgetProject.php:44)
[stacktrace]
#0 /var/www/html/portal.coloredcow.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Modules\\Project\\Console\\FixedBudgetProject->handle()
#1 /var/www/html/portal.coloredcow.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#2 /var/www/html/portal.coloredcow.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#3 /var/www/html/portal.coloredcow.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#4 /var/www/html/portal.coloredcow.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#5 /var/www/html/portal.coloredcow.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#6 /var/www/html/portal.coloredcow.com/vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute()
#7 /var/www/html/portal.coloredcow.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#8 /var/www/html/portal.coloredcow.com/vendor/symfony/console/Application.php(1040): Illuminate\\Console\\Command->run()
#9 /var/www/html/portal.coloredcow.com/vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand()
#10 /var/www/html/portal.coloredcow.com/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#11 /var/www/html/portal.coloredcow.com/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
#12 /var/www/html/portal.coloredcow.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#13 /var/www/html/portal.coloredcow.com/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#14 {main}
"} 
```

**Comment by GauravGusain98** [comment]
> ```
> getMailForFixedBudgetProjectKeyAccountManagers
> ```

@Satendra-SR This error is not related to this issue.

**Comment by deepakbarmola** [comment]
This was in relation to session token expiry.
